### ISSUE TITLE
ImportError: cannot import name 'getMedias'

### ISSUE THREAD

**Issue by thexwts** [Spark-NF/twitter_media_downloader#1] opened 2017-04-01 23:00 UTC
RESTART: C:\Users\KaliTut\AppData\Local\Programs\Python\Python36-32\TMDM\twitter_media_downloader.py 
Traceback (most recent call last):
  File "C:\Users\KaliTut\AppData\Local\Programs\Python\Python36-32\TMDM\twitter_media_downloader.py", line 6, in <module>
    from parser import getMedias
ImportError: cannot import name 'getMedias'

**Comment by Spark-NF** [comment] 2017-07-12 15:33
Closing for duplication and moving to issue #3.
Please provide more information in that issue if the problem is still happening. :smile:

**Closed by Spark-NF** 2017-07-12 15:33 UTC
Labels: bug, cant-reproduce
