### ISSUE TITLE
getMedias 

### ISSUE THREAD

**Issue by thexwts** [Spark-NF/twitter_media_downloader#3] opened 2017-04-03 19:46 UTC
when ever i try to run twitter_media_downloader.py i get this error 
in both python 3 & 2
Traceback (most recent call last):
  File "I:\Downloads\Compressed\twitter_media_downloader-master\twitter_media_downloader-master\twitter_media_downloader.py", line 9, in <module>
    from parser import getMedias
ImportError: cannot import name 'getMedias'

**Comment by Spark-NF** [comment] 2017-11-16 18:18
Closing since I couldn't reproduce on either 2.x or 3.x.
If you still have the issue, please provide your environment information and I'll re-open. 👌

**Comment by Bambr-name** [comment] 2017-12-16 20:34
Hi!
I have same issue;

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\twitter_media_downloader-master>twitter_media_downloader.py
Traceback (most recent call last):
  File "C:\twitter_media_downloader-master\twitter_media_downloader.py", line 9, in <module>
    from parser import getMedias
ImportError: cannot import name getMedias

**Comment by Bionus** [comment] 2017-12-16 21:14
@Bambr-name can you tell me which Python version you're using? (`python --version`)
Also, what's the result of `pip list`?

**Comment by Spark-NF** [comment] 2017-12-16 21:15
@Bambr-name can you tell me which Python version you're using? (`python --version`)
Also, what's the result of `pip list`?

**Comment by Bambr-name** [comment] 2017-12-16 23:18
C:\Python27>python --version
Python 2.7.13

C:\Python27>pip list
beautifulsoup4 (4.6.0)
bs4 (0.0.1)
numpy (1.13.3)
pandas (0.21.1)
pip (9.0.1)
python-dateutil (2.6.1)
pytz (2017.3)
setuptools (28.8.0)
six (1.11.0)

C:\Python27>

**Closed** 2018-02-22 10:19 UTC
Labels: bug, cant-reproduce
